In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('insurance_pre.csv')

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
datasets=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [6]:
datasets

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [8]:
indep=datasets[['age', 'sex_male', 'bmi', 'children', 'smoker_yes']]
dep=datasets[['charges']]

In [9]:
from sklearn.ensemble import RandomForestRegressor

In [11]:
from sklearn.model_selection import GridSearchCV
param_grid = {
        'criterion':['squared_error','absolute_error'],
        'max_features': ['sqrt','log2'],
        'n_estimators':[10,100]
}
grid = GridSearchCV(RandomForestRegressor(), param_grid, refit = True, verbose = 3,n_jobs=-1)
grid.fit(indep, dep)

Fitting 5 folds for each of 8 candidates, totalling 40 fits

C:\Users\swadh\anaconda4\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error'],
                         'max_features': ['sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             verbose=3)

In [12]:
re=grid.cv_results_
print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'criterion': 'squared_error', 'max_features': 'log2', 'n_estimators': 100}:

In [13]:
table=pd.DataFrame.from_dict(re)

In [14]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.198298,0.002303,0.023079,0.001372,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.841519,0.761663,0.829354,0.812008,0.818562,0.812621,0.027377,7
1,1.437155,0.027475,0.082830,0.004430,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.857485,0.779602,0.856453,0.827635,0.844188,0.833072,0.028827,2
2,0.172227,0.023853,0.024644,0.002150,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.836175,0.761844,0.837509,0.813396,0.799926,0.809770,0.027834,8
3,1.362636,0.015352,0.075710,0.002465,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.854460,0.777897,0.863634,0.830945,0.838577,0.833103,0.029902,1
4,0.478271,0.023656,0.023760,0.002891,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.830938,0.778849,0.842385,0.822419,0.826035,0.820125,0.021709,5
5,3.824345,0.030630,0.053968,0.005862,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.857686,0.777791,0.854966,0.828993,0.844947,0.832877,0.029321,4
6,0.466333,0.012243,0.022230,0.001768,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.834066,0.752655,0.839555,0.815143,0.839978,0.816279,0.033073,6
7,3.638642,0.046062,0.043357,0.003198,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.858334,0.780564,0.858978,0.828479,0.838815,0.833034,0.028707,3

In [15]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 25
BMI: 50
Children: 30
Sex Male 0 or 1: 2
Smoker Yes 0 or 1: 5

In [16]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[24203.6583488]

C:\Users\swadh\anaconda4\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(