In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('insurance_pre.csv')

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
datasets=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [5]:
datasets

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [8]:
indep=datasets[['age', 'sex_male', 'bmi', 'children', 'smoker_yes']]
dep=datasets[['charges']]

In [10]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [12]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid = {'kernel':['rbf','poly','sigmoid','linear'],
'C':[10,100,1000,2000,3000],'gamma':['auto','scale']}
# fitting the model for grid search
grid = GridSearchCV(SVR(), param_grid, refit = True, verbose = 3,n_jobs=-1)
grid.fit(X_train, y_train)

Fitting 5 folds for each of 40 candidates, totalling 200 fits

C:\Users\swadh\anaconda4\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'poly', 'sigmoid', 'linear']},
             verbose=3)

In [13]:
re=grid.cv_results_
print("TheR_score valueforbestparameter{}:".format(grid.best_params_))

TheR_score valueforbestparameter{'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}:

In [14]:
 table=pd.DataFrame.from_dict(re)

In [15]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.277114,0.025524,0.117471,0.033305,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",-0.004176,0.022594,-0.118956,-0.082926,-0.103473,-0.057387,0.056205,35
1,0.210966,0.023146,0.064283,0.022039,10,auto,poly,"{'C': 10, 'gamma': 'auto', 'kernel': 'poly'}",0.047420,0.077536,-0.060527,-0.009476,-0.050823,0.000826,0.054025,32
2,0.272420,0.053889,0.072734,0.017801,10,auto,sigmoid,"{'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.044787,0.081689,-0.072355,-0.027541,-0.051470,-0.004978,0.058648,34
3,0.162585,0.005495,0.035079,0.004624,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",0.387624,0.461268,0.288301,0.340540,0.297825,0.355112,0.063693,25
4,0.212615,0.004493,0.083900,0.003673,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",-0.003956,0.022453,-0.119035,-0.082925,-0.103510,-0.057395,0.056230,36
5,0.147253,0.004169,0.032727,0.003121,10,scale,poly,"{'C': 10, 'gamma': 'scale', 'kernel': 'poly'}",0.043648,0.079780,-0.059229,-0.009498,-0.050317,0.000877,0.053658,31
6,0.195742,0.003962,0.044738,0.001504,10,scale,sigmoid,"{'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.043946,0.082230,-0.072132,-0.027546,-0.051337,-0.004968,0.058595,33
7,0.137266,0.008221,0.029493,0.002466,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",0.387624,0.461268,0.288301,0.340540,0.297825,0.355112,0.063693,25
8,0.202683,0.007296,0.091110,0.012295,100,auto,rbf,"{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}",0.303414,0.319385,0.155546,0.208414,0.161756,0.229703,0.069348,29
9,0.156118,0.008060,0.039188,0.004496,100,auto,poly,"{'C': 100, 'gamma': 'auto', 'kernel': 'poly'}",0.542212,0.566743,0.471172,0.537557,0.413719,0.506281,0.056081,22
10,0.248982,0.016823,0.059556,0.007047,100,auto,sigmoid,"{'C': 100, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.492088,0.545107,0.438714,0.468576,0.425516,0.474000,0.042447,23
11,0.194837,0.014024,0.043070,0.004116,100,auto,linear,"{'C': 100, 'gamma': 'auto', 'kernel': 'linear'}",0.596232,0.635776,0.566816,0.588799,0.537415,0.585008,0.032600,19
12,0.248308,0.006527,0.089467,0.006180,100,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",0.304939,0.318480,0.155033,0.208422,0.161488,0.229672,0.069604,30
13,0.191967,0.015794,0.037323,0.004932,100,scale,poly,"{'C': 100, 'gamma': 'scale', 'kernel': 'poly'}",0.532310,0.571466,0.474948,0.537506,0.415264,0.506299,0.055077,21
14,0.227258,0.006283,0.041806,0.003486,100,scale,sigmoid,"{'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.491855,0.544604,0.439299,0.468556,0.424226,0.473708,0.042461,24
15,0.172674,0.007671,0.030299,0.003166,100,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",0.596232,0.635776,0.566816,0.588799,0.537415,0.585008,0.032600,19
16,0.248657,0.008431,0.084466,0.008200,1000,auto,rbf,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}",0.731430,0.716349,0.686476,0.710172,0.613293,0.691544,0.041718,11
17,0.210575,0.021353,0.040780,0.004114,1000,auto,poly,"{'C': 1000, 'gamma': 'auto', 'kernel': 'poly'}",0.799185,0.786769,0.821307,0.810704,0.719528,0.787499,0.035885,8
18,0.249472,0.014768,0.048073,0.005570,1000,auto,sigmoid,"{'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.232428,0.306815,0.236688,0.291707,0.346868,0.282901,0.043415,28
19,0.218207,0.011890,0.036863,0.002833,1000,auto,linear,"{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}",0.686126,0.598398,0.586104,0.573860,0.556109,0.600119,0.045217,13
20,0.258561,0.011732,0.078823,0.004967,1000,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",0.732079,0.715992,0.686057,0.710177,0.613122,0.691485,0.041876,12
21,0.217500,0.010344,0.033257,0.003155,1000,scale,poly,"{'C': 1000, 'gamma': 'scale', 'kernel': 'poly'}",0.798212,0.787019,0.823118,0.810712,0.719979,0.787808,0.036003,7
22,0.232270,0.010564,0.046672,0.004893,1000,scale,sigmoid,"{'C': 1000, 'gamma': 'scale', 'kernel': 'sigmo...",0.248266,0.377692,0.315321,0.291779,0.346175,0.315846,0.044478,27
23,0.211916,0.011127,0.031605,0.003197,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",0.686126,0.598398,0.586104,0.573860,0.556109,0.600119,0.045217,13
24,0.267642,0.010081,0.082113,0.004918,2000,auto,rbf,"{'C': 2000, 'gamma': 'auto', 'kernel': 'rbf'}",0.788746,0.764261,0.818616,0.794131,0.709676,0.775086,0.036986,9
25,0.416432,0.162799,0.032812,0.003017,2000,auto,poly,"{'C': 2000, 'gamma': 'auto', 'kernel': 'poly'}",0.804603,0.784782,0.847674,0.807280,0.745448,0.797957,0.033268,4
26,0.230071,0.012806,0.047064,0.001843,2000,auto,sigmoid,"{'C': 2000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.656854,-0.432695,-0.346330,-0.484052,-0.076409,-0.399268,0.190629,38
27,0.251256,0.017347,0.032206,0.002714,2000,auto,linear,"{'C': 2000, 'gamma': 'auto', 'kernel': 'linear'}",0.669958,0.592446,0.586953,0.572862,0.556109,0.595666,0.039218,15
28,0.264251,0.007719,0.080898,0.007701,2000,scale,rbf,"{'C': 2000, 'gamma': 'scale', 'kernel': 'rbf'}",0.789144,0.764022,0.818319,0.794133,0.709586,0.775041,0.036992,10
29,0.515542,0.436040,0.032923,0.001742,2000,scale,poly,"{'C': 2000, 'gamma': 'scale', 'kernel': 'poly'}",0.804708,0.784713,0.847781,0.807295,0.745732,0.798046,0.033220,3
30,0.225981,0.003303,0.048591,0.003127,2000,scale,sigmoid,"{'C': 2000, 'gamma': 'scale', 'kernel': 'sigmo...",-0.370980,-0.421011,-0.350248,-0.483750,-0.087414,-0.342681,0.135687,37
31,0.265540,0.017461,0.034630,0.002748,2000,scale,linear,"{'C': 2000, 'gamma': 'scale', 'kernel': 'linear'}",0.669958,0.592446,0.586953,0.572862,0.556109,0.595666,0.039218,15
32,0.302387,0.007561,0.080120,0.003086,3000,auto,rbf,"{'C': 3000, 'gamma': 'auto', 'kernel': 'rbf'}",0.795104,0.772917,0.846181,0.811601,0.725697,0.790300,0.040188,5
33,0.813096,0.515481,0.031436,0.010057,3000,auto,poly,"{'C': 3000, 'gamma': 'auto', 'kernel': 'poly'}",0.804915,0.783304,0.852190,0.810160,0.748175,0.799749,0.034104,2
34,0.240058,0.008554,0.053052,0.006060,3000,auto,sigmoid,"{'C': 3000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-1.795299,-1.629662,-1.461919,-1.712710,-0.929359,-1.505790,0.308601,39
35,0.321737,0.053731,0.029705,0.003532,3000,auto,linear,"{'C': 3000, 'gamma': 'auto', 'kernel': 'linear'}",0.669819,0.588893,0.587076,0.572849,0.557014,0.595130,0.039068,17
36,0.296993,0.009478,0.085169,0.005730,3000,scale,rbf,"{'C': 3000, 'gamma': 'scale', 'kernel': 'rbf'}",0.795353,0.772801,0.846034,0.811601,0.725615,0.790281,0.040189,6
37,0.455218,0.090014,0.028354,0.006015,3000,scale,poly,"{'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}",0.805169,0.783163,0.852345,0.810160,0.748201,0.799808,0.034165,1
38,0.230869,0.008027,0.044817,0.002090,3000,scale,sigmoid,"{'C': 3000, 'gamma': 'scale', 'kernel': 'sigmo...",-1.651895,-2.010670,-1.468842,-1.712109,-0.961821,-1.561068,0.346643,40
39,0.223238,0.029911,0.017207,0.000519,3000,scale,linear,"{'C': 3000, 'gamma': 'scale', 'kernel': 'linear'}",0.669819,0.588893,0.587076,0.572849,0.557014,0.595130,0.039068,17

In [16]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 32
BMI: 43
Children: 2
Sex Male 0 or 1: 0
Smoker Yes 0 or 1: 1

In [23]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[1.91233462e+08]